Classes/Controller/AbstractController.php, ext_localconf.php
For compatibility with TYPO3 7.5
=> Bugfix: className must not start with a backslash

composer.json
When using composer to install and deploy TYPO3 the current version requirement of the cms-core will give you an error: Skipped branch develop, Could not parse version constraint >=6.2.*: Invalid version string "6.2.*"
Also if static_info_tables are not required by another package they will be missing why it's important to have them as a requirement also.
=> [BUGFIX] Corrected invalid version requirement and added static_info_tables

Classes/Domain/Model/ReadableInterface.php
Interface "ReadableInterface" is not found because there is a typo in the name "Readableinterface" (lowercase name).
=> [BUGFIX] Fixed interface name (camel case)

Classes/Ajax/Dispatcher.php
The TypoScript Frontend Controller is initialized in 
```php
\Mittwald\Typo3Forum\Ajax\Dispatcher::initializeTsfe()
```
and 
```php
\Mittwald\Typo3Forum\Ajax\Dispatcher::initTYPO3()
```
later on, where the latter one overrides the former one. This leads to a broken TypoScript setup in *$GLOBALS['TSFE']->tmpl->setup* and causes the AJAX Controller to be unable to resolve root paths and the storage page ID. This is, why the menu buttons ('Subscribe', 'New topic', …) aren't ever displayed.
=> Stop AJAX Dispatcher from initializing TSFE twice

.travis.yml
@pstranghoener has different plans for the documentation. As the doc build is currently failing anyway, simply remove it for now.
Instead, add a simple test to check the correct syntax of PHP files in the repository. Just because I can.
Fixes #122.
=> Don't test documentation build in CI run

ext_tables_static+adt.sql
* Change default value of type field in table `tx_typo3forum_domain_model_format_textparser`
* Fix data for import into table `tx_typo3forum_domain_model_format_textparser`
* Fix data for import into table `tx_typo3forum_domain_model_moderation_reportworkflowstatus`
* Fix data for import into table `tx_typo3forum_domain_model_user_userfield_userfield`
* Rename `tx_typo3forum_domain_model_moderation_reportworkflowstatus_followup` to `tx_typo3forum_domain_model_moderation_reportworkflowstatus_mm` as already mentioned in Classes/Scheduler/DatabaseMigrator.php
=> [BUGFIX] Update ext_tables_static+adt.sql with proper columns and data in type field

Classes/Configuration/ConfigurationBuilder.php, Classes/Controller/AjaxController.php, Classes/Domain/Factory/AbstractFactory.php, Classes/Domain/Model/Forum/Attachment.php, Classes/Domain/Model/Forum/Topic.php, Classes/Domain/Model/User/FrontendUser.php, Classes/Domain/Repository/AbstractRepository.php, Classes/Service/Mailing/AbstractMailingService.php, Classes/Service/Notification/NotificationService.php, Classes/ViewHelpers/Ext/UserLinkViewHelper.php, ext_tables.sql
- Add database keys for relations
- Load and parse typoscript only once via singleton
- use a common interface to load plugin configuration
- load and parse only typo3_forum typoscript, not the whole thing
- get rid of `new` (which led to multiple instances of typoscript parsing during the display of multiple topics)
=> TASK: improve performance

composer.json
Fixes the replace configuration in composer.json to install the extension to the correct folder typo3_forum with composer.
See #191
=> TASK: fix replace configuration in composer.json

Classes/Cache/CacheManager.php
fixes exception for second foreach() if glob() returns false (happens if folder is empty)
=> fixes exception for CacheManager::deleteTemporaryFiles()

Classes/Service/Mailing/HTMLMailingService.php
Hi everyone,
Subscribing without an email address leads to the following, when creating a new Post or Topic:
Address in mailbox given [] does not comply with RFC 2822. 
This PR adds an early return if a recipient has no email set.
Had to fix this for one of our projects and might as well provide it to the public.
Cheers,
Jonathan
=> Don't send an email if FontendUser has no email adress set

Classes/Domain/Model/ConfigurableInterface.php, Classes/Domain/Model/Forum/Topic.php, Classes/Domain/Model/User/FrontendUser.php, Classes/Service/Notification/NotificationService.php, Classes/Service/SettingsHydrator.php, ext_localconf.php
While creating a new post, settings are not injected into the current topic which leads to incorrect page number computation (division by 0).
This PR fixes the problem
=> Fixes topics DI in subscriber notifications

Classes/Controller/PostController.php
At the moment some HTML code is attached to the download. So some files are corrupt and can't be opened afterwards. 
See: #230
=> Fix attachment download

Classes/Controller/TopicController.php, Configuration/TypoScript/setup.txt
Make sending a HTTP 'PURGE' request, which clears the cache for caching
proxies like varnish optional by adding a TypoScript option 'purgeCache'
which is enabled by default to keep the current behaviour. Currently a
PURGE request is only sent to a forum on creating a topic for it.
=> Add TS option to disable PURGE on creating topic

Configuration/TCA/tx_typo3forum_domain_model_forum_topic.php
Changing the forum of a topic which has posts in Backend failed (at
least on PostgreSQL) as due to the `uid` column being set as
`foreign_sortby` the TYPO3 RelationHandler tried to update the `uid` of
the post (!!). In order to circumvent this until RelationHandler is
fixed do not sort posts of a topic in backend.
=> Fix changing forum of a topic in Backend

Configuration/TCA/tx_typo3forum_domain_model_forum_topic.php
When editing a topic which does not have a solution yet display '-'
instead of 'Invalid value [0]'
=> Fix display of topics without solution in backend

ext_localconf.php
On deleting a topic from moderation an exception '#1297933823: Object of
type Mittwald\Typo3Forum\Domain\Model\Forum\Topic with identity "X" not
found' was shown as the action was not marked as uncached. This patch
marks the topicConformDeleteAction() as uncached which fixes the issue.
=> Fix exception on deleting topic

Classes/Domain/Model/ConfigurableEntityTrait.php
In order to be able to debug Typo3Forum\Domain\Model objects using
DebuggerUtility::var_dump() or <f:debug/> $settings must be set to
protected instead of private.
=> Make ConfigurableEntityTrait::$settings protected

Classes/Scheduler/ForumRead.php
As PostgreSQL has strict case sensitivity checks the SQL query for the
column "lastLogin" fails there as it is defined as "lastlogin" in the
definition and in the database.
=> Fix SQL error in ForumRead scheduler task on PostgreSQL

Resources/Private/Templates/Bootstrap/ViewHelpers/Widget/Paginate/Index.html, Resources/Private/Templates/Standard/ViewHelpers/Widget/Paginate/Index.html
Instead of displaying disabled links (and a link to the current page, if
items <= itemsPerPage) hide the pagination completely in those cases.
=> Show pagination only if needed

Classes/Configuration/ConfigurationBuilder.php
Throw an InvalidConfigurationException stating the reason if the
TypoScript configuration of typo3_forum is missing (mostly due to the
static template not having been included in a template or via an
extension typoscript file.
=> Throw InvalidConfigurationException on missing TypoScript

Resources/Private/Partials/Bootstrap/User/InformationRow.html, Resources/Private/Partials/Bootstrap/User/List.html, Resources/Private/Partials/Bootstrap/User/ListTopUser.html, Resources/Private/Partials/Standard/User/InformationRow.html, Resources/Private/Partials/Standard/User/List.html, Resources/Private/Partials/Standard/User/ListTopUser.html, Resources/Private/Templates/Bootstrap/User/Index.html, Resources/Private/Templates/Standard/User/Index.html
Several templates did not use the `dateFormat` and `dateTimeFormat`
settings from TypoScript but defined the format themselves. This patch
unifies the usage by using the TypoScript settings everywhere.
=> Unified dateFormat and dateTimeFormat usage

Classes/Domain/Model/Forum/Post.php
When checking for moderation permissions in a post the check for the
"moderators" usergroup defined by `fe_groups.user_mod` was forgotten.
This patch adds the check allowing members of such a group to edit and
delete posts from the Topic->showAction().
=> [BUGFIX] Respect fe_groups.user_mod in Post->checkEditOrDeletePostAccess()

Configuration/TypoScript/constants.txt, Configuration/TypoScript/setup.txt, Resources/Private/Partials/Bootstrap/Post/Single.html, Resources/Private/Partials/Standard/Post/Single.html
This patch makes it possible to show posted image attachments (png,jpg)
by setting the TypoScript constant
`plugin.tx_typo3forum.settings.showPostImagesInline = 1`
Views of the post will not increase the download counter for the
attachment.
=> [FEATURE] Allow optional inline display of posted image attachments

Configuration/TCA/tx_typo3forum_domain_model_forum_attachment.php
An attachment allows only one file. This patch changes TCA to display
the attachment in BE as a single-file selector instead of multiple.
=> Fix TCA display of attachment

Classes/Scheduler/Counter.php
The execution of the Counter task in scheduler led to SQL errors (at
least on PostgreSQL). Simplifying the queries and using `Connection`
instead of `QueryBuilder` to execute the updates where possible fixes
this.
=> Fix SQL errors in scheduler task `Counter`

Classes/Service/Notification/NotificationService.php, Classes/Service/Notification/SubscriptionListener.php, Resources/Private/Language/locallang.xml
It was possible to subscribe to a forum like to a topic, but
notifications for new topics in a forum were never sent as this was not
implemented. This patch is based on code by @AMartinNo1 from
https://github.com/mittwald/typo3_forum/issues/184 and
implements the missing notifications to forum subscriptions.
Notifications are only sent once to a user even if the user subscribed
to a forum and its subforum and a topic is created in the subforum.
Translations for the new labels `Mail_Subscribe_NewPost_Subject` and
`Mail_Subscribe_NewPost_Body` have been added to English and German
only.
Fixes https://github.com/mittwald/typo3_forum/issues/184
=> Add notifications for forum subscriptions

Classes/Scheduler/ForumRead.php
Forums without topics were always marked as new, also forums containing
subforums without posts - this patch marks those forums as read in the
ForumRead scheduler task, which before only handled forums containing
topics.
Depends on https://github.com/mittwald/typo3_forum/pull/304
Fixes https://github.com/mittwald/typo3_forum/issues/250
=> Mark forums without topics as read in ForumRead scheduler task

Classes/ViewHelpers/Forum/RootlineViewHelper.php, Resources/Private/Templates/Bootstrap/Forum/Show.html, Resources/Private/Templates/Bootstrap/Moderation/EditReport.html, Resources/Private/Templates/Bootstrap/Topic/Show.html, Resources/Private/Templates/Standard/Forum/Show.html, Resources/Private/Templates/Standard/Moderation/EditReport.html, Resources/Private/Templates/Standard/Topic/Show.html
This patch allows to define classes for the icons of forum and topic in
the rootline (omitting the icons completely if not set) and allows to
use breadcrumb instead of nav-pills (which is configured as default for
the bootstrap templates).
This patch also fixes the "reverse" attribute, which did not work yet.
=> [FEATURE] Allow defining of classes for RootlineViewHelper items

Classes/Domain/Model/User/FrontendUser.php, Classes/Domain/Model/User/FrontendUserGroup.php, Configuration/TCA/Overrides/fe_groups.php, Configuration/TCA/Overrides/fe_users.php, Resources/Private/Language/locallang_db.xml
This patch renames and improves the label for fe_groups.user_mod,
improves the according PHPDoc and removes the no longer valid third
parameter to addTCAcolumns()
=> Improve fe_groups.user_mod usage

Configuration/TCA/tx_typo3forum_domain_model_forum_forum.php, Configuration/TCA/tx_typo3forum_domain_model_forum_post.php, Configuration/TCA/tx_typo3forum_domain_model_forum_topic.php
This patch improves the TCA of Forum, Post and Topic by adding exclude-
properties to several columns and adds columns so they can be edited in
the TYPO3 backend.
Requires https://github.com/mittwald/typo3_forum/pull/284 to be merged
first in order to avoid conflicts.
=> [FEATURE] Allow granular permissions for Forum, Post and Topic

Classes/Domain/Validator/Forum/PostValidator.php, Classes/Updates/PostsWithoutAuthorNameUpdate.php, ext_localconf.php
This patch restores the authorName validation for anonymous users, which
was removed only in parts (and maybe  accidental).
The validation code for the author name of anonymous users was disabled
(maybe accidentally?) in 07-2013 by commit 6f04ca0d "[TASK] cache opt.".
The complete class was removed in 07-2015 by commit 3ae2f46e
"[TASK] Various code cleanups".
An update wizards takes care of invalid authorNames by setting
'Anonymous' for empty authorNames and prepending 'Anonymous: ' for
authorNames with one or two chars.
=> [FEATURE] Restore authorName validation for anonymous users

ext_emconf.php
The `dependencies` definition in `ext_emconf.php` using a comma
separated string is not used anymore since < TYPO3 6.2. Remove the
definition.
Fixes: https://github.com/mittwald/typo3_forum/issues/274
=> Remove old dependencies definition

Configuration/TCA/tx_typo3forum_domain_model_forum_topic.php
The "readers" column of Topics was shown twice when opening the record
in the Backend-TCA. This patch removes one of the definitions.
=> [BUGFIX] Display "readers" column only once in Topic-TCA

Resources/Private/Templates/Bootstrap/ViewHelpers/Widget/Paginate/Index.html
In the Bootstrap template the CSS class "page-link" was missing on the
link to the first page (bug visible only after selecting another page).
This patch displays the link correctly in the same style as the others.
=> [BUGFIX] Correctly display pagebrowser link to first page

Configuration/TCA/tx_typo3forum_domain_model_forum_forum.php
Use the same sorting definition for topics in Backend when editing a
forum like in Frontend (sticky first, then by newest post)
=> [BUGFIX] Sort topics of a forum in BE like in FE

Classes/Updates/PostsWithoutAuthorNameUpdate.php
Avoid a `MysqliException` `Unknown fetch type '7'` when executing the
upgrade wizard `PostsWithoutAuthorNameUpdate` on MySQL by using the
`fetchColumn()` method instead of `fetch(PDO::FETCH_COLUMN)`.
=> [BUGFIX] Avoid SQL error in PostsWithoutAuthorNameUpdate on MySQL

Configuration/TCA/Overrides/fe_users.php
Commit d795a992 `[TASK] reports & mod function` in 07-2013 added a TCA
config overriding the `fe_users.disable` column type from `check` to
`passthrough` which hides the field in the backend making it impossible
to disable fe_users records there. This was probably not on purpose as
there are no negative side effects when editing the record in the
backend.
This patch removes the override in order to re-enable the functionality
to disable fe_users in the backend.
=> [BUGFIX] Show "disable" option for fe_users in backend again

Configuration/TCA/Overrides/fe_users.php
The three columns rank, use_gravatar and contact were not defined as
exclude=1 in TCA of fe_users leading to admins not having the
possibility to deny access to those. This patch adds the exclude
definitions for those columns.
=> [BUGFIX] Add missing exclude definitions for fe_user columns

ext_tables.sql
A separate definition setting the character set for the cache tables is
not needed in any current version of TYPO3 as UTF-8 always is default.
In contrast it causes issues with databases configured to use `utf8mb4`.
In order to simply use the database default as all other tables do this
patch removes the character set definitions for the cache tables.
Fixes: #333
=> [BUGFIX] Remove character set definitions for cache tables

Classes/Service/Notification/NotificationService.php, Resources/Private/Language/locallang.xml
When the 'onTopicCreated' signal is sent the new topic has not been
persisted yet. This leads to current notifications for new topics being
sent with an invalid link (as it does not contain a topic uid)
Changing this would change the signal for other extensions using the
signal. Instead of doing so this patch makes the notification for a new
topic behave like one for a new post: Send a link to the parent object
(here the forum) and the name of the object (here the topic) instead.
=> [BUGFIX] Send link to forum instead of topic in new topic notification

Resources/Private/Language/locallang.xml
This patch fixes the english translations for `Mail_Subscribe_NewPost_Body` and `Mail_Subscribe_NewTopic_Body` which were mixed up and did not contain the fixes of https://github.com/AgenturPottkinder/typo3_forum/commit/8e2d22e5ff716d5c3a56dd7dec04875c8983a85d#diff-7e8e3103f38f06fd377c7adae66f6c85
Fixes: https://github.com/AgenturPottkinder/typo3_forum/issues/352
=> [BUGFIX] Correct translations for notifications

Classes/ViewHelpers/User/AvatarViewHelper.php
A missing image should not throw an exception so a check if the image exists should be done
=> Check if image exists to avoid ViewHelper Exception
